# site settings
title: Ke
subtitle: He
email: kh695640204@gmail.com
description: Computer Science graduate interested in interpretable deep learning.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ke He
street_address: 220 Old West Coast Road
city: Christchurch
state: Canterbury
zip_code: 7676
country: New Zealand
phone: (021) 253-4346

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/Kihy
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
